export {default as LandingPage} from './LandingPage';
export {default as HomePage} from "./HomePage"
export {default as SignupPage} from "./SignupPage"
export {default as LoginPage} from "./LoginPage"
export {default as DashBoard} from './DashBoard'
export {default as NotFoundPage} from '../pages/NotFoundPage'
export {default as RoutesPage} from '../pages/RoutesPage'
export {default as SearchTrain} from './SearchTrain'
export {default as About} from './About'